In [1]:
import numpy as np
h=0
t=0
mat = np.random.randint(1,20,(3,3))
print(mat)
toss_mat=mat.copy()
for i in range(0,3):
    for j in range(0,3):
        if toss_mat[i,j]%3==0:
            h+=1
            toss_mat[i,j]=0
        else:
            t+=1
            toss_mat[i,j]=1

print(toss_mat)
print("no of head=",h,"and no of tail=",t)
get_h=h/9
print('probability of getting head=',get_h)
print('probability of getting tail =',1-get_h)

[[17 17 11]
 [15 14  2]
 [ 4 10 16]]
[[1 1 1]
 [0 1 1]
 [1 1 1]]
no of head= 1 and no of tail= 8
probability of getting head= 0.1111111111111111
probability of getting tail = 0.8888888888888888


In [2]:
for iteration in range(5):
    h = 0
    t = 0
    mat = np.random.randint(1, 20, (3, 3))
    print(f"Iteration {iteration + 1}:")
    print("Original Matrix:")
    print(mat)
    
    toss_mat = mat.copy()
    for i in range(0, 3):
        for j in range(0, 3):
            if toss_mat[i, j] % 3 == 0:
                h += 1
                toss_mat[i, j] = 0
            else:
                t += 1
                toss_mat[i, j] = 1
    
    print("Toss Result Matrix:")
    print(toss_mat)
    print("Number of heads =", h, "and number of tails =", t)
    get_h = h / 9
    print("Probability of getting head =", get_h)
    print("Probability of getting tail =", 1 - get_h)
    print()

Iteration 1:
Original Matrix:
[[13 16 10]
 [13 11 19]
 [12 14  3]]
Toss Result Matrix:
[[1 1 1]
 [1 1 1]
 [0 1 0]]
Number of heads = 2 and number of tails = 7
Probability of getting head = 0.2222222222222222
Probability of getting tail = 0.7777777777777778

Iteration 2:
Original Matrix:
[[ 8 11  2]
 [14 11  3]
 [11 15 16]]
Toss Result Matrix:
[[1 1 1]
 [1 1 0]
 [1 0 1]]
Number of heads = 2 and number of tails = 7
Probability of getting head = 0.2222222222222222
Probability of getting tail = 0.7777777777777778

Iteration 3:
Original Matrix:
[[18 11 15]
 [ 5 19 15]
 [15  4 13]]
Toss Result Matrix:
[[0 1 0]
 [1 1 0]
 [0 1 1]]
Number of heads = 4 and number of tails = 5
Probability of getting head = 0.4444444444444444
Probability of getting tail = 0.5555555555555556

Iteration 4:
Original Matrix:
[[14 15 15]
 [11 18 19]
 [13  3  8]]
Toss Result Matrix:
[[1 0 0]
 [1 0 1]
 [1 0 1]]
Number of heads = 4 and number of tails = 5
Probability of getting head = 0.4444444444444444
Probability of get

In [3]:
k=0
for k in range(0,5):
    print(k,"th iteration")
    h=0
    t=0
    mat = np.random.randint(1,20,(3,3))
    print(mat)
    toss_mat=mat.copy()
    for i in range(0,3):
       for j in range(0,3):
            if toss_mat[i,j]%3==0:
                 h+=1
                 toss_mat[i,j]=0
            else:
                 t+=1
                 toss_mat[i,j]=1
       print(toss_mat)
       print("no of head=",h,"and no of tail=",t)
       get_h=h/9
       print('probability of getting head=',get_h)
       print('probability of getting tail =',1-get_h)
       k+=1
    

0 th iteration
[[18  3  1]
 [ 5 16 17]
 [18  2  4]]
[[ 0  0  1]
 [ 5 16 17]
 [18  2  4]]
no of head= 2 and no of tail= 1
probability of getting head= 0.2222222222222222
probability of getting tail = 0.7777777777777778
[[ 0  0  1]
 [ 1  1  1]
 [18  2  4]]
no of head= 2 and no of tail= 4
probability of getting head= 0.2222222222222222
probability of getting tail = 0.7777777777777778
[[0 0 1]
 [1 1 1]
 [0 1 1]]
no of head= 3 and no of tail= 6
probability of getting head= 0.3333333333333333
probability of getting tail = 0.6666666666666667
1 th iteration
[[13 14 11]
 [12  9 18]
 [ 4  1 10]]
[[ 1  1  1]
 [12  9 18]
 [ 4  1 10]]
no of head= 0 and no of tail= 3
probability of getting head= 0.0
probability of getting tail = 1.0
[[ 1  1  1]
 [ 0  0  0]
 [ 4  1 10]]
no of head= 3 and no of tail= 3
probability of getting head= 0.3333333333333333
probability of getting tail = 0.6666666666666667
[[1 1 1]
 [0 0 0]
 [1 1 1]]
no of head= 3 and no of tail= 6
probability of getting head= 0.33333333333333

In [4]:
import numpy as np
# from IPython.display import HTML

total_h=0
for k in range(5):
    print(k,' iteration')
    # h1 = ''
    # t1= ''
    h=0
    t=0
    mat = np.random.randint(1, 20, (3, 3))
    
    print(mat)
    
    toss_mat = mat.copy()
    for i in range(0, 3):
        for j in range(0, 3):
            if toss_mat[i, j] % 3 == 0:
                h +=1
                toss_mat[i, j] = 0
            else:
                t += 1
                toss_mat[i, j] = 1
    
    
    print(toss_mat)
    print("Number of heads =", h, "and number of tails =", t)
    get_h = h / 9
    print("Probability of getting head =", get_h)
    print("Probability of getting tail =", 1 - get_h)
    
    total_h= total_h+h
p_h = total_h/45
print("probab of getting H (all events combined)",p_h)
print("probab of getting H (all events combined)",1-p_h)


    


0  iteration
[[ 2 19  9]
 [ 1 16 16]
 [ 2  1  5]]
[[1 1 0]
 [1 1 1]
 [1 1 1]]
Number of heads = 1 and number of tails = 8
Probability of getting head = 0.1111111111111111
Probability of getting tail = 0.8888888888888888
1  iteration
[[16  9  5]
 [ 3  9 17]
 [ 3  6 15]]
[[1 0 1]
 [0 0 1]
 [0 0 0]]
Number of heads = 6 and number of tails = 3
Probability of getting head = 0.6666666666666666
Probability of getting tail = 0.33333333333333337
2  iteration
[[ 1 13  1]
 [17  3  9]
 [16  6 13]]
[[1 1 1]
 [1 0 0]
 [1 0 1]]
Number of heads = 3 and number of tails = 6
Probability of getting head = 0.3333333333333333
Probability of getting tail = 0.6666666666666667
3  iteration
[[ 9  5  3]
 [15  1  7]
 [ 2 12  9]]
[[0 1 0]
 [0 1 1]
 [1 0 0]]
Number of heads = 5 and number of tails = 4
Probability of getting head = 0.5555555555555556
Probability of getting tail = 0.4444444444444444
4  iteration
[[10  7 19]
 [14  7 14]
 [16  5 11]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Number of heads = 0 and number of tails =

In [5]:
import numpy as np

total_h = 0

for k in range(5):
    print(k, 'iteration')
    h = 0
    t = 0
    mat = np.random.randint(1, 20, (3, 3))
    
    print(mat)
   
    # toss_mat = mat.copy()
   
    display_mat = np.empty((3,3),dtype=object)
   
    # for i in range(0, 3):
    #     for j in range(0, 3):
    #         if toss_mat[i, j] % 3 == 0:
    #             h += 1
    #             display_mat[i, j] = 'h'
    #             toss_mat[i, j] = 1 
    #         else:
    #             t += 1
    #             display_mat[i, j] = 't'
    #             toss_mat[i, j] = 0  
    
    
    display_mat[mat%3==0]='h'
   
    display_mat[mat%3!=0]='t'
    # if mat[mat%3==0]:
    #     h+=1
    # else:
    #     t+=1
    h = np.count_nonzero(display_mat == 'h')
    t = np.count_nonzero(display_mat == 't')



    
    print(display_mat)
    print("Number of heads =", h, "and number of tails =", t)
    get_h = h / 9
    print("Probability of getting head =", get_h)
    print("Probability of getting tail =", 1 - get_h)
    
    total_h = total_h + h

p_h = total_h / 45
print("Probability of getting H (all events combined)", p_h)
print("Probability of getting T (all events combined)", 1 - p_h)
# e = time.time()
# print(e-s)

0 iteration
[[ 1  4  5]
 [ 3 12  7]
 [ 3  6 16]]
[['t' 't' 't']
 ['h' 'h' 't']
 ['h' 'h' 't']]
Number of heads = 4 and number of tails = 5
Probability of getting head = 0.4444444444444444
Probability of getting tail = 0.5555555555555556
1 iteration
[[11 10  4]
 [19  8  4]
 [15  8 12]]
[['t' 't' 't']
 ['t' 't' 't']
 ['h' 't' 'h']]
Number of heads = 2 and number of tails = 7
Probability of getting head = 0.2222222222222222
Probability of getting tail = 0.7777777777777778
2 iteration
[[14  9 18]
 [ 3  2 14]
 [ 6  8 12]]
[['t' 'h' 'h']
 ['h' 't' 't']
 ['h' 't' 'h']]
Number of heads = 5 and number of tails = 4
Probability of getting head = 0.5555555555555556
Probability of getting tail = 0.4444444444444444
3 iteration
[[16  8 13]
 [17 11  8]
 [ 1 14  5]]
[['t' 't' 't']
 ['t' 't' 't']
 ['t' 't' 't']]
Number of heads = 0 and number of tails = 9
Probability of getting head = 0.0
Probability of getting tail = 1.0
4 iteration
[[16  5 18]
 [13 14 14]
 [11 15  4]]
[['t' 't' 'h']
 ['t' 't' 't']
 ['